# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cleanArchitecture+coordinator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'RxAlamofire'
  pod 'AlamofireNetworkActivityLogger'
  pod 'RxSwift'
  pod 'AlamofireObjectMapper', :git => 'https://github.com/RomanPodymov/AlamofireObjectMapper.git', :branch => 'master'
  pod 'RxCocoa'
  pod 'ObjectMapper'
  pod 'AlamofireImage'

  # Pods for cleanArchitecture+coordinator

  target 'cleanArchitecture+coordinatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cleanArchitecture+coordinatorUITests' do
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
