# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mvvm+rxswift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'AlamofireNetworkActivityLogger'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'mvvm+rxswiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mvvm+rxswiftUITests' do
    # Pods for testing
  end

end
